In [1]:
from dataset import LOBSTERLevel10Dataset, load_dfs
from torch.utils.data import DataLoader

books, _ = load_dfs()

train_data = LOBSTERLevel10Dataset(train=True)
train_loader = DataLoader(train_data, shuffle=False, batch_size=64)

In [2]:
batch = next(iter(train_loader))

In [3]:
batch.shape

torch.Size([64, 40])

In [4]:
books.head(64)

,ASKp1,ASKs1,BIDp1,BIDs1,ASKp2,ASKs2,BIDp2,BIDs2,ASKp3,ASKs3,...,BIDp8,BIDs8,ASKp9,ASKs9,BIDp9,BIDs9,ASKp10,ASKs10,BIDp10,BIDs10
0,2239500,100,2231800,100,2239900,100,2230700,200,2240000,220,...,2202500,5000,2294300,100,2202000,100,2298000,100,2189700,100
1,2239500,100,2238100,21,2239900,100,2231800,100,2240000,220,...,2204000,100,2294300,100,2202500,5000,2298000,100,2202000,100
2,2239500,100,2238100,21,2239600,20,2231800,100,2239900,100,...,2204000,100,2267700,100,2202500,5000,2294300,100,2202000,100
3,2239500,100,2238100,21,2239600,20,2237500,100,2239900,100,...,2213000,4000,2267700,100,2204000,100,2294300,100,2202500,5000
4,2239500,100,2238100,21,2239600,20,2237500,100,2239900,100,...,2213000,4000,2267700,100,2204000,100,2294300,100,2202500,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2240000,1411,2237500,74,2242400,20,2236500,2,2242500,100,...,2230000,10,2267700,100,2226200,100,2294300,100,2213000,4000
60,2240000,1338,2237500,74,2242400,20,2236500,2,2242500,100,...,2230000,10,2267700,100,2226200,100,2294300,100,2213000,4000
61,2240000,1318,2237500,74,2242400,20,2236500,2,2242500,100,...,2230000,10,2267700,100,2226200,100,2294300,100,2213000,4000
62,2240000,1314,2237500,74,2242400,20,2236500,2,2242500,100,...,2230000,10,2267700,100,2226200,100,2294300,100,2213000,4000
63,2240000,1311,2237500,74,2242400,20,2236500,2,2242500,100,...,2230000,10,2267700,100,2226200,100,2294300,100,2213000,4000

In [5]:
LOBSTERLevel10Dataset.feature_sequence_to_df(batch, books.loc[0])

,ASKp1,ASKs1,BIDp1,BIDs1,ASKp2,ASKs2,BIDp2,BIDs2,ASKp3,ASKs3,...,BIDp8,BIDs8,ASKp9,ASKs9,BIDp9,BIDs9,ASKp10,ASKs10,BIDp10,BIDs10
0,2239500.0,100.000000,2231800.0,100.0,2239900.0,100.000000,2230700.0,200.0,2240000.0,220.0,...,2202500.0,5000.000000,2294300.0,100.000000,2202000.0,100.000000,2298000.0,100.000000,2189700.0,100.000000
1,2239500.0,100.000000,2238100.0,21.0,2239900.0,100.000000,2231800.0,100.0,2240000.0,220.0,...,2204000.0,100.000000,2294300.0,100.000000,2202500.0,5000.000488,2298000.0,100.000000,2202000.0,100.000000
2,2239500.0,100.000000,2238100.0,21.0,2239600.0,19.999998,2231800.0,100.0,2239900.0,100.0,...,2204000.0,100.000000,2267700.0,100.000000,2202500.0,5000.000488,2294300.0,100.000000,2202000.0,100.000000
3,2239500.0,100.000000,2238100.0,21.0,2239600.0,19.999998,2237500.0,100.0,2239900.0,100.0,...,2213000.0,3999.999756,2267700.0,100.000000,2204000.0,100.000000,2294300.0,100.000000,2202500.0,5000.000488
4,2239500.0,100.000000,2238100.0,21.0,2239600.0,19.999998,2237500.0,100.0,2239900.0,100.0,...,2213000.0,3999.999756,2267700.0,100.000000,2204000.0,100.000000,2294300.0,100.000000,2202500.0,5000.000488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2239999.5,1410.999878,2237499.5,74.0,2242399.5,20.000000,2236499.5,2.0,2242499.5,100.0,...,2229999.5,9.999997,2267699.5,99.999992,2226199.5,99.999985,2294299.5,99.999992,2212999.5,3999.999512
60,2239999.5,1337.999878,2237499.5,74.0,2242399.5,20.000000,2236499.5,2.0,2242499.5,100.0,...,2229999.5,9.999997,2267699.5,99.999992,2226199.5,99.999985,2294299.5,99.999992,2212999.5,3999.999512
61,2239999.5,1317.999878,2237499.5,74.0,2242399.5,20.000000,2236499.5,2.0,2242499.5,100.0,...,2229999.5,9.999997,2267699.5,99.999992,2226199.5,99.999985,2294299.5,99.999992,2212999.5,3999.999512
62,2239999.5,1313.999878,2237499.5,74.0,2242399.5,20.000000,2236499.5,2.0,2242499.5,100.0,...,2229999.5,9.999997,2267699.5,99.999992,2226199.5,99.999985,2294299.5,99.999992,2212999.5,3999.999512
63,2239999.5,1310.999878,2237499.5,74.0,2242399.5,20.000000,2236499.5,2.0,2242499.5,100.0,...,2229999.5,9.999997,2267699.5,99.999992,2226199.5,99.999985,2294299.5,99.999992,2212999.5,3999.999512

In [6]:
import numpy as np

books.head(64)['BIDp5']

0     2226200
1     2230000
2     2230000
3     2230400
4     2230400
       ...
59    2235000
60    2235000
61    2235000
62    2235000
63    2235000
Name: BIDp5, Length: 64, dtype: int64

In [7]:
LOBSTERLevel10Dataset.feature_sequence_to_df(batch, books.loc[0])['BIDp5']

0     2226200.0
1     2230000.0
2     2230000.0
3     2230400.0
4     2230400.0
        ...
59    2234999.5
60    2234999.5
61    2234999.5
62    2234999.5
63    2234999.5
Name: BIDp5, Length: 64, dtype: float32

In [8]:
np.mean(np.pow(books.head(64)['BIDp5'] - LOBSTERLevel10Dataset.feature_sequence_to_df(batch, books.loc[0])['BIDp5'], 2))

np.float64(0.0498046875)